### ISSUE TITLE
How do you do per-process hotkeys?

### ISSUE THREAD

**Issue by abdullah-kasim** [Miigon/mkhd#1]
In `skhd`, we could add the following to `~/.skhdrc`:

```bash
cmd - right [
  "Google Chrome" ~
  "Firefox" ~
   * : do-some-command
]
```

This would bind `cmd - right` to run `do-some-command` in all processes except for Firefox and Chrome.

Is it possible to do the same in `mkhd`?

**Comment by Miigon** [comment]
Yes it does still support this. I forgot to add it to the example config.
It's as follows:
```bash
# process specific binding
cmd - right [
  "Google Chrome" .fallthrough # do nothing when in google chrome
  "Terminal" .nop # do nothing and eat the keypress when in terminal
  "Firefox" : echo "i'm in firefox!!"
   * : echo "i'm in anything else except chrome and firefox and terminal"
]
```
