### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by Nathan-ma** [Miigon/mkhd#2]
Just to let you know how happy I am rn! Great changes, great fork! this is awesome!

My problem and how mkhd solved it:

I use Yabai and I normally move focus to another window with `hyper - ]` or `hyper - [`, but I had to set another keybind just to swap the windows.

Muscle memory was hitting me hard when doing this, so, I had a plan: what if i can `hyper + lcmd`?

My shkd won't allow me to remap hyper 😢 .

Behold what mhkd can do:

```
.alias $hyper lcmd + lalt + lshift + rctrl
.alias $cmd_hyper $hyper + lcmd

## swap window
$cmd_hyper - 0x21 : yabai -m window --swap west --focus east
$cmd_hyper - 0x1E : yabai -m window --swap east --focus west

# cycle through windows
$hyper - 0x21 : yabai -m window --focus stack.prev || yabai -m window --focus prev || yabai -m window --focus last # 0x21 stands for '['
$hyper - 0x1E : yabai -m window --focus stack.next || yabai -m window --focus next || yabai -m window --focus first # 0x1E  stands for ']'
```

Thank you kind sir, this fork is amazing!

**Comment by Miigon** [comment]
Glad you liked it!
